#!/usr/bin/env bash

mysql -h ${MARIADB_HOST} -u root -p${MARIADB_ROOT_PASSWORD} -e "DROP DATABASE IF EXISTS ${MARIADB_DATABASE}; CREATE DATABASE ${MARIADB_DATABASE}; GRANT ALL PRIVILEGES ON  ${MARIADB_DATABASE}.* to '${MARIADB_USER}'@'%' WITH GRANT OPTION;"
